AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
  BloggingEventsTableName:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/dynamodb/blogging-events/name
  BloggingEventsStream:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/dynamodb/blogging-events/stream
  CockroachDBDsnForArticle:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/cockroachdb/dsn/article
  CockroachDBDsnForTag:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/cockroachdb/dsn/tag
  NewRelicAppName:
    Type: String
  NewRelicLicenseKey:
    NoEcho: true
    Type: String
  BlogPublishEndpoint:
    NoEcho: true
    Type: String
  GitHubToken:
    NoEcho: true
    Type: String

Resources:
  BloggingEventSubscriber:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub BloggingEvent-Subscriber-${Env}
      CodeUri: ../bootstrap.zip
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        BloggingEvent:
          Type: DynamoDB
          Properties:
            BatchSize: 100
            BisectBatchOnFunctionError: true
            MaximumRetryAttempts: 3
            StartingPosition: TRIM_HORIZON
            Stream: !Ref BloggingEventsStream
            FilterCriteria:
              Filters:
                - Pattern: '{ "eventName" : { "S" : [ "INSERT" ] } }'
      Environment:
        Variables:
          ENV: !Ref Env
          BLOGGING_EVENTS_TABLE_NAME: !Ref BloggingEventsTableName
          COCKROACHDB_DSN_ARTICLE: !Ref CockroachDBDsnForArticle
          COCKROACHDB_DSN_TAG: !Ref CockroachDBDsnForTag
          NEW_RELIC_CONFIG_APP_NAME: !Ref NewRelicAppName
          NEW_RELIC_CONFIG_LICENSE: !Ref NewRelicLicenseKey
          BLOG_PUBLISH_ENDPOINT: !Ref BlogPublishEndpoint
          GITHUB_TOKEN: !Ref GitHubToken
      Timeout: 900
      Policies:
        - Statement:
          - Sid: DynamoDBStreamPolicy
            Effect: Allow
            Action:
              - dynamodb:DescribeStream
              - dynamodb:GetShardIterator
              - dynamodb:GetRecords
              - dynamodb:ListStreams
            Resource: "*"
          - Sid: DynamoDBPolicy
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
            Resource: "*"
          - Sid: CloudWatchLogsPolicy
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
    Metadata:
      BuildMethod: go1.x

  BloggingEventSubscriberLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${BloggingEventSubscriber}
      RetentionInDays: 30


