version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/core/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/core/echo/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/core/grpc/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/core/graphql/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/article-service/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tag-service/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/federator/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"