// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"blogapi.miyamo.today/article-service/internal/app/usecase"
	"blogapi.miyamo.today/article-service/internal/configs/di/provider"
	"blogapi.miyamo.today/article-service/internal/if-adapter/presenter/pb/convert"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func GetEchoApp() *echo.Echo {
	db := provider.SQLDB()
	queries := provider.QueryService(db)
	getByID := usecase.NewGetByID(queries)
	listAll := usecase.NewListAll(queries)
	listAfter := usecase.NewListAfter(queries)
	listBefore := usecase.NewListBefore(queries)
	convertGetByID := convert.NewGetByID()
	convertListAll := convert.NewListAll()
	convertListAfter := convert.NewListAfter()
	convertListBefore := convert.NewListBefore()
	articleServiceServer := provider.ArticleServiceServer(getByID, listAll, listAfter, listBefore, convertGetByID, convertListAll, convertListAfter, convertListBefore)
	application := provider.NewRelic()
	echoEcho := Echo(articleServiceServer, application)
	return echoEcho
}
