// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miyamo2/blogapi.miyamo.today/article-service/internal/configs/di/provider"
	pb2 "github.com/miyamo2/blogapi.miyamo.today/article-service/internal/if-adapter/controller/pb"
	"github.com/miyamo2/blogapi.miyamo.today/article-service/internal/if-adapter/presenter/pb"
	"github.com/miyamo2/blogapi.miyamo.today/article-service/internal/infra/rdb/query"
)

// Injectors from wire.go:

func GetDependencies() *Dependencies {
	application := provider.NewRelic()
	server := provider.GRPCServer(application)
	articleService := query.NewArticleService()
	getById := provider.GetByIdUsecase(articleService)
	getAll := provider.GetAllUsecase(articleService)
	getNext := provider.GetNextUsecase(articleService)
	getPrev := provider.GetPrevUsecase(articleService)
	converter := pb.NewConverter()
	articleServiceServer := pb2.NewArticleServiceServer(getById, getAll, getNext, getPrev, converter, converter, converter, converter)
	dialector := provider.GormDialector()
	dependencies := NewDependencies(server, application, articleServiceServer, dialector)
	return dependencies
}
