// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miyamo2/blogapi.miyamo.today/federator/internal/app/usecase"
	"github.com/miyamo2/blogapi.miyamo.today/federator/internal/configs/di/provider"
	"github.com/miyamo2/blogapi.miyamo.today/federator/internal/if-adapter/controller/graphql/resolver"
	"github.com/miyamo2/blogapi.miyamo.today/federator/internal/if-adapter/presenters/graphql/converter"
)

// Injectors from wire.go:

func GetDependencies() *Dependencies {
	articleServiceClient := provider.ArticleClient()
	article := usecase.NewArticle(articleServiceClient)
	articles := usecase.NewArticles(articleServiceClient)
	tagServiceClient := provider.TagClient()
	tag := usecase.NewTag(tagServiceClient)
	tags := usecase.NewTags(tagServiceClient)
	usecases := provider.Usecases(article, articles, tag, tags)
	converterConverter := converter.NewConverter()
	converters := provider.Converters(converterConverter, converterConverter, converterConverter, converterConverter)
	resolverResolver := resolver.NewResolver(usecases, converters)
	config := provider.GqlgenConfig(resolverResolver)
	executableSchema := provider.GqlgenExecutableSchema(config)
	application := provider.NewRelic()
	server := provider.GqlgenServer(executableSchema, application)
	echo := provider.Echo(server, application)
	dependencies := NewDependencies(echo)
	return dependencies
}
