name: release

on:
  push:
    tags:
      - "v*"
      - "**/v*"

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config --global url."https://${{ secrets.READ_MY_PRIVATE_REPO_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.0"
          cache: true
          cache-dependency-path: go.sum

      - name: Go Test
        run: |
          go test ./... -v -coverpkg=./... -coverprofile=coverage.tmp.out | tee test_output.txt
          exit ${PIPESTATUS[0]}

      - name: Excluded unnecessary modules from coverage.
        run: |
          cat coverage.tmp.out | grep -v "mock" | grep -v "github.com/miyamo2/blogapi-core/infra/dynamodb/client" > coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          fail_ci_if_error: false
          verbose: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{  github.ref_name }}
          generate_release_notes: true
