name: "Deploy"
inputs:
  repository:
    description: "repository name"
    required: true
  target:
    description: "target to deploy"
    required: true
  app_id:
    description: "GitHub App ID"
    required: true
  app_private_key:
    description: "GitHub App Private Key"
    required: true
  commit_sha:
    description: "Commit SHA"
    required: true
  github_secret:
    description: "GitHub Secret"
    required: true
    default: ""
  owner:
    description: "repository owner"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}
        owner: ${{ inputs.owner }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ inputs.owner }}
        password: ${{ inputs.github_secret }}
        #password: ${{ steps.generate-token.outputs.token }}

    - name: Build & Push Docker Image
      working-directory: ${{ inputs.target }}
      shell: bash
      run: |
        docker build -t ghcr.io/${{ inputs.repository }}:${{ inputs.target }}-${{ inputs.commit_sha }} -f ./.build/package/Dockerfile .
        docker push ghcr.io/${{ inputs.repository }}:${{ inputs.target }}-${{ inputs.commit_sha }}

    - name: Dispatch manifest update
      uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
      with:
        token: ${{ steps.generate-token.outputs.token }}
        repository: miyamo2/manifest.miyamo.today
        event-type: ${{ inputs.target }}
        client-payload: |-
          {
            "target": "${{ inputs.target }}",
            "tag": "${{ inputs.commit_sha }}"
          }
