// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package tag

import (
	"context"
)

// iteratorForPreTagArticles implements pgx.CopyFromSource.
type iteratorForPreTagArticles struct {
	rows                 []PreTagArticlesParams
	skippedFirstNextCall bool
}

func (r *iteratorForPreTagArticles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPreTagArticles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TagID,
		r.rows[0].Title,
		r.rows[0].Thumbnail,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForPreTagArticles) Err() error {
	return nil
}

func (q *Queries) PreTagArticles(ctx context.Context, arg []PreTagArticlesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tmp_articles"}, []string{"id", "tag_id", "title", "thumbnail", "created_at", "updated_at"}, &iteratorForPreTagArticles{rows: arg})
}
