// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/configs/di/provider"
	"github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/if-adapter/presenter/pb"
)

// Injectors from wire.go:

func GetDependencies() *Dependencies {
	config := provider.AWSConfig()
	application := provider.NewRelic()
	server := provider.GRPCServer(application)
	bloggingEventCommandService := provider.BloggingEventCommandService()
	createArticle := provider.CreateArticleUsecase(bloggingEventCommandService)
	converter := pb.NewConverter()
	updateArticleTitle := provider.UpdateArticleTitleUsecase(bloggingEventCommandService)
	updateArticleBody := provider.UpdateArticleBodyUsecase(bloggingEventCommandService)
	updateArticleThumbnail := provider.UpdateArticleThumbnailUsecase(bloggingEventCommandService)
	attachTags := provider.AttachTagsUsecase(bloggingEventCommandService)
	bloggingEventServiceServer := provider.NewBloggingEventServiceServer(createArticle, converter, updateArticleTitle, converter, updateArticleBody, converter, updateArticleThumbnail, converter, attachTags, converter)
	dialector := provider.GormDialector(config)
	dependencies := NewDependencies(config, server, application, bloggingEventServiceServer, dialector)
	return dependencies
}
