// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/configs/di/provider"
	pb2 "github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/if-adapter/controller/pb"
	"github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/if-adapter/presenter/pb"
)

// Injectors from wire.go:

func GetDependencies() *Dependencies {
	config := provider.AWSConfig()
	application := provider.NewRelic()
	server := provider.GRPCServer(application)
	bloggingEventCommandService := provider.BloggingEventCommandService()
	createArticle := provider.CreateArticleUsecase(bloggingEventCommandService)
	converter := pb.NewConverter()
	bloggingEventServiceServer := pb2.NewBloggingEventServiceServer(createArticle, converter)
	dialector := provider.GormDialector(config)
	dependencies := NewDependencies(config, server, application, bloggingEventServiceServer, dialector)
	return dependencies
}
