// Code generated by MockGen. DO NOT EDIT.
// Source: converter.go
//
// Generated by this command:
//
//	mockgen -source=converter.go -destination=../../../../mock/if-adapter/controller/pb/presenter/converter.go -package=presenters
//

// Package presenters is a generated GoMock package.
package presenters

import (
	context "context"
	reflect "reflect"

	dto "github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/app/usecase/dto"
	grpc "github.com/miyamo2/blogapi.miyamo.today/blogging-event-service/internal/infra/grpc"
	gomock "go.uber.org/mock/gomock"
)

// MockToCreateArticleResponse is a mock of ToCreateArticleResponse interface.
type MockToCreateArticleResponse struct {
	ctrl     *gomock.Controller
	recorder *MockToCreateArticleResponseMockRecorder
	isgomock struct{}
}

// MockToCreateArticleResponseMockRecorder is the mock recorder for MockToCreateArticleResponse.
type MockToCreateArticleResponseMockRecorder struct {
	mock *MockToCreateArticleResponse
}

// NewMockToCreateArticleResponse creates a new mock instance.
func NewMockToCreateArticleResponse(ctrl *gomock.Controller) *MockToCreateArticleResponse {
	mock := &MockToCreateArticleResponse{ctrl: ctrl}
	mock.recorder = &MockToCreateArticleResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToCreateArticleResponse) EXPECT() *MockToCreateArticleResponseMockRecorder {
	return m.recorder
}

// ToCreateArticleArticleResponse mocks base method.
func (m *MockToCreateArticleResponse) ToCreateArticleArticleResponse(ctx context.Context, from *dto.CreateArticleOutDto) (*grpc.BloggingEventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToCreateArticleArticleResponse", ctx, from)
	ret0, _ := ret[0].(*grpc.BloggingEventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToCreateArticleArticleResponse indicates an expected call of ToCreateArticleArticleResponse.
func (mr *MockToCreateArticleResponseMockRecorder) ToCreateArticleArticleResponse(ctx, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToCreateArticleArticleResponse", reflect.TypeOf((*MockToCreateArticleResponse)(nil).ToCreateArticleArticleResponse), ctx, from)
}
