// Code generated by MockGen. DO NOT EDIT.
// Source: get_by_id.go
//
// Generated by this command:
//
//	mockgen -source=get_by_id.go -destination=../../../../mock/if-adapter/controller/pb/usecase/mock_get_by_id.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	dto "github.com/miyamo2/blogapi.miyamo.today/article-service/internal/app/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockGetById is a mock of GetById interface.
type MockGetById struct {
	ctrl     *gomock.Controller
	recorder *MockGetByIdMockRecorder
	isgomock struct{}
}

// MockGetByIdMockRecorder is the mock recorder for MockGetById.
type MockGetByIdMockRecorder struct {
	mock *MockGetById
}

// NewMockGetById creates a new mock instance.
func NewMockGetById(ctrl *gomock.Controller) *MockGetById {
	mock := &MockGetById{ctrl: ctrl}
	mock.recorder = &MockGetByIdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetById) EXPECT() *MockGetByIdMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetById) Execute(ctx context.Context, in dto.GetByIdInDto) (*dto.GetByIdOutDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*dto.GetByIdOutDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetByIdMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetById)(nil).Execute), ctx, in)
}
