// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miyamo2/blogapi.miyamo.today/tag-service/internal/configs/di/provider"
	pb2 "github.com/miyamo2/blogapi.miyamo.today/tag-service/internal/if-adapter/controller/pb"
	"github.com/miyamo2/blogapi.miyamo.today/tag-service/internal/if-adapter/presenter/pb"
	"github.com/miyamo2/blogapi.miyamo.today/tag-service/internal/infra/rdb/query"
)

// Injectors from wire.go:

func GetDependencies() *Dependencies {
	application := provider.NewRelic()
	server := provider.GRPCServer(application)
	tagService := query.NewTagService()
	getById := provider.GetByIdUsecase(tagService)
	converter := pb.NewConverter()
	getAll := provider.GetAllUsecase(tagService)
	getNext := provider.GetNextUsecase(tagService)
	getPrev := provider.GetPrevUsecase(tagService)
	tagServiceServer := pb2.NewTagServiceServer(getById, converter, getAll, converter, getNext, converter, getPrev, converter)
	dialector := provider.GormDialector()
	dependencies := NewDependencies(server, application, tagServiceServer, dialector)
	return dependencies
}
