// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"blogapi.miyamo.today/tag-service/internal/app/usecase"
	"blogapi.miyamo.today/tag-service/internal/configs/di/provider"
	"blogapi.miyamo.today/tag-service/internal/if-adapter/presenter/pb/convert"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func GetEchoApp() *echo.Echo {
	db := provider.SQLDB()
	queries := provider.QueryService(db)
	getById := usecase.NewGetById(queries)
	getByIdTag := convert.NewGetByIdTag()
	listAll := usecase.NewListAll(queries)
	getAllTags := convert.NewGetAllTags()
	listAfter := usecase.NewListAfter(queries)
	getNextTags := convert.NewGetNextTags()
	listBefore := usecase.NewListBefore(queries)
	getPrevTags := convert.NewGetPrevTags()
	tagServiceServer := provider.TagServiceServer(getById, getByIdTag, listAll, getAllTags, listAfter, getNextTags, listBefore, getPrevTags)
	application := provider.NewRelic()
	echoEcho := Echo(tagServiceServer, application)
	return echoEcho
}
