name: ci_go

on:
  push:
    branches:
      - "feature/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
      - "release/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "release/**"
  workflow_call:

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config --global url."https://${{ secrets.READ_MY_PRIVATE_REPO_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.0"
          cache: true
          cache-dependency-path: go.sum

      - name: Go Build
        run: |
          go mod tidy
          go build -v ./...

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: staticcheck with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          staticcheck ./... | reviewdog -f=staticcheck -reporter=github-pr-check -level warning

      - name: Go Test
        run: |
          go test ./... -v -coverpkg=./... -coverprofile=coverage.tmp.out | tee test_output.txt
          exit ${PIPESTATUS[0]}

      - name: Create Coverage Report to PR comment
        if: github.event_name == 'pull_request'
        run: |
          cat coverage.tmp.out | grep -v "mock" | grep -v "configs" | grep -v "infra/fw/gqlgen" > coverage.out
          go tool cover -func=coverage.out | awk '/total/ {print "| **" $1 "** | **" $3 "** |"}' | tee coverage.txt
          cat test_output.txt | grep 'ok.*coverage' | awk '{print "| " $2 " | " $5 " |"}' | tee -a coverage.txt
          echo "## Test Coverage Report" > coverage_with_header.txt
          echo "| Package           | Coverage |" >> coverage_with_header.txt
          echo "|-------------------|----------|" >> coverage_with_header.txt
          cat coverage.txt >> coverage_with_header.txt
          mv coverage_with_header.txt coverage.txt
          rm test_output.txt

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body-path: "coverage.txt"
