name: ci

on:
  push:
    branches:
      - "feature/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
      - "release/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "release/**"
  workflow_call:

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [">=1.21.0"]
        module:
          [
            article/client,
            article/server,
            tag/client,
            tag/server,
            blogging_event/client,
            blogging_event/server,
          ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goversion }}

      - name: Go Build
        working-directory: ${{ matrix.module }}
        run: |
          go mod tidy
          go build -v ./...

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup staticcheck
        working-directory: ${{ matrix.module }}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: staticcheck with reviewdog
        working-directory: ${{ matrix.module }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          staticcheck ./... | reviewdog -f=staticcheck -reporter=github-pr-check -level warning
