name: ci_article_service

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
      - "main"
    paths:
      - "article-service/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "article-service/**"
  workflow_call:

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: .github/custom_actions/ci/
        with:
          target: article-service
          upload_codecov: true
