name: ci_blogging-event-service

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
      - "main"
    paths:
      - "blogging-event-service/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "blogging-event-service/**"
  workflow_call:

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/custom_actions/ci/
        with:
          target: blogging-event-service
          upload_codecov: true
