name: ci_core_graphql

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
    paths:
      - "core/graphql/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "core/graphql/**"

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/custom_actions/ci/
        with:
          target: core/graphql
