name: ci_core_grpc

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
    paths:
      - "core/grpc/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "core/grpc/**"

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Git Config
        run: |
          git config --global url."https://${{ secrets.READ_MY_PRIVATE_REPO_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.0"
          cache: true
          cache-dependency-path: go.sum

      - name: Go Build
        working-directory: core/grpc
        run: |
          go mod tidy
          go build -v ./...

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup staticcheck
        working-directory: core/grpc
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: staticcheck with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: core/grpc
        run: |
          staticcheck ./... | reviewdog -f=staticcheck -reporter=github-pr-check -level warning

      - name: Go Test
        working-directory: core/grpc
        run: |
          go test ./... -v -coverpkg=./... -coverprofile=coverage
          exit ${PIPESTATUS[0]}
