name: ci_core_echo

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "bugfix/**"
      - "hotfix/**"
    paths:
      - "core/echo/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "core/echo/**"

permissions: write-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/custom_actions/ci/
        with:
          target: core/echo
