name: deploy_blogging-event-service

on:
  push:
    branches:
      - "main"
    paths:
      - "blogging-event-service/**"
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blogging-event-service

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/custom_actions/deploy/
        with:
          target: blogging-event-service
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          commit_sha: ${{ github.sha }}
          repository: ${{ github.repository }}
          owner: ${{ github.repository_owner }}