name: deploy_federator

on:
  push:
    branches:
      - "main"
    paths:
      - "federator/**"
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: federator

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/custom_actions/deploy/
        with:
          target: federator
          app_id: ${{ secrets.GH_APP_ID }}
          app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          gcp_project: ${{ secrets.GCP_PROJECT_ID }}
          gcp_credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
          gcp_region: ${{ secrets.GCP_REGION }}
          commit_sha: ${{ github.sha }}
          owner: ${{ github.repository_owner }}