name: release_core

on:
  push:
    branches: [main]
    paths: ["core/CHANGELOG.md"]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: "~1.25.0"
          cache: true
          cache-dependency-path: go.sum

      - name: Setup mockgen
        run: |
          go install go.uber.org/mock/mockgen@latest

      - name: Go Generate
        working-directory: core
        run: |
          go mod tidy
          go generate ./...
          git diff --exit-code

      - name: Unit Test
        working-directory: core
        run: |
          TARGET=$(go list ./... | grep -v "mock")
          go test $TARGET -v -p 1 -coverprofile=coverage.out
          exit ${PIPESTATUS[0]}

      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ github.workspace }}
          file: ${{ github.workspace }}/core/coverage
          fail_ci_if_error: false
          verbose: true
          flags: core

      - name: Extract Version
        id: versioning
        working-directory: core
        run: |
          VERSION="core/v$(sed -n 's/##\s\([0-9.]*\)\s.*/\1/p' CHANGELOG.md | head -1)"
          echo ::set-output name=version::$VERSION

      - name: Extract changes from prev version
        working-directory: core
        run: |
          git fetch --prune --unshallow
          PRETAG=$(git tag --sort -v:refname | grep core/v | head -1)
          CURRENTTAG=${{ steps.versioning.outputs.version }}
          echo "## What's Changed in ${CURRENTTAG}" > diff-changelog.txt
          if [ -z "$PRETAG" ]
          then
            cat CHANGELOG.md | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g' | sed -e 's/##\s[0-9.]*\s.*//g' | sed -e '/^$/d' >> diff-changelog.txt
          else
            git diff $PRETAG..${{ github.sha }} -- CHANGELOG.md | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g' | sed -e 's/##\s[0-9.]*\s.*//g' | sed -e '/^$/d' >> diff-changelog.txt
            echo "" >> diff-changelog.txt
            echo "**Full Changelog**: https://github.com/miyamo2/api.miyamo.today/compare/${PRETAG}...${CURRENTTAG}" >> diff-changelog.txt
          fi

      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          generate_release_notes: false
          body_path: core/diff-changelog.txt
