name: staging_deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  staging_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Git Config
        run: |
          git config --global url."https://${{ secrets.READ_MY_PRIVATE_REPO_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Set up aws cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"

      - name: Build
        working-directory: ./read-model-updater
        run: |
          GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap ./cmd
          zip bootstrap.zip bootstrap

      - name: Deploy
        working-directory: ./read-model-updater/.deploy
        run: |
          sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.SAM_ARTIFACTS_BUCKET_NAME_DEV }}
          sam deploy --template-file packaged.yaml --stack-name miyamo-today-read-model-updater-dev --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            NewRelicAppName=miyamo-today-api-read-model-updater-dev \
            NewRelicLicenseKey=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
            BlogPublishEndpoint=${{ secrets.BLOG_PUBLISH_ENDPOINT }} \
            GitHubToken=${{ secrets.READ_MY_PRIVATE_REPO_TOKEN }} \
            NewRelicAccountId=${{ secrets.NEW_RELIC_ACCOUNT_ID }} \
            --no-fail-on-empty-changeset
